# Generated by Django 5.0.6 on 2025-03-31 21:09

import Listings.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=None, max_length=200)),
                ('event_name', models.TextField(blank=True, max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=15)),
                ('slots_available', models.PositiveIntegerField(default=None)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_from', models.TimeField(default=Listings.models.get_current_time)),
                ('time_to', models.TimeField(default=Listings.models.get_default_time)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(blank=True, max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('is_urban', models.BooleanField(default=True)),
                ('potential_interest', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('is_furnished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='Non_negative_price'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', datetime.date(2025, 3, 31))), name='Date_must_not_be_in_the_past'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('time_to__gte', models.F('time_from'))), name='Time_to_must_be_after_time_from'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='seen_listings',
            field=models.ManyToManyField(blank=True, related_name='seen_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
