# Generated by Django 5.0.6 on 2025-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField(default=None, max_length=200)),
                ('event_name', models.TextField(blank=True, max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=15)),
                ('slots_available', models.PositiveIntegerField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('prop_name', models.TextField(blank=True, max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(default=None, max_length=200)),
                ('location', models.TextField(max_length=15)),
                ('address', models.CharField(default='<django.db.models.fields.TextField>', max_length=15)),
                ('is_urban', models.BooleanField(default=True)),
                ('potential_interest', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField(default=None)),
                ('bathrooms', models.PositiveIntegerField(default=None)),
                ('is_furnished', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
