# Generated by Django 5.0.6 on 2025-03-03 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_alter_event_id_alter_propertylisting_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='created_at',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='seen_listings',
            field=models.ManyToManyField(blank=True, related_name='seen_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='location',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='prop_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
