# Generated by Django 5.0.6 on 2025-03-26 10:45

import Listings.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_event_date_event_time_from_event_time_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.TimeField(default=Listings.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.TimeField(default=Listings.models.get_default_time),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='Non_negative_price'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('date__gte', datetime.date(2025, 3, 26))), name='Date_must_not_be_in_the_past'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('time_to__gte', models.F('time_from'))), name='Time_to_must_be_after_time_from'),
        ),
    ]
